name: Build, Push and Deploy (Docker)

on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            rafacarreras05/Rafa-grancapitan:latest
            rafacarreras05/Rafa-grancapitan:${{ github.sha }}

      - name: Deploy to EC2 via SSH
        if: ${{ secrets.EC2_HOST != '' && secrets.EC2_USER != '' && secrets.EC2_SSH_KEY != '' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            docker pull rafacarreras05/Rafa-grancapitan:latest
            docker stop Rafa-grancapitan || true
            docker rm Rafa-grancapitan || true
            docker run -d \
              --name Rafa-grancapitan \
              --restart unless-stopped \
              -p 5000:5000 \
              rafacarreras05/Rafa-grancapitan:latest
            docker image prune -f
